steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 
           'gcr.io/${PROJECT_ID}/techpuzzle8-repo/techpuzzle8', 
           '.']

  # Docker Push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 
           'gcr.io/${PROJECT_ID}/techpuzzle8-repo/techpuzzle8:latest']

  # Entrypoint, timeout and environment variables
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    timeout: 240s
    args: ['compute', 'instances', 
           'update-container', 'nginx-vm',
           '--container-image', 
           'gcr.io/${PROJECT_ID}/techpuzzle8-repo/techpuzzle8:latest']
    env:
      - 'CLOUDSDK_COMPUTE_REGION=us-central1'
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
